/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicEchofaceEndpointRouteImport } from './routes/api.public.echoface.$endpoint'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEchofaceEndpointRoute =
  ApiPublicEchofaceEndpointRouteImport.update({
    id: '/api/public/echoface/$endpoint',
    path: '/api/public/echoface/$endpoint',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/api/public/echoface/$endpoint': typeof ApiPublicEchofaceEndpointRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/api/public/echoface/$endpoint': typeof ApiPublicEchofaceEndpointRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/api/public/echoface/$endpoint': typeof ApiPublicEchofaceEndpointRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connect' | '/dashboard' | '/api/public/echoface/$endpoint'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connect' | '/dashboard' | '/api/public/echoface/$endpoint'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/dashboard'
    | '/api/public/echoface/$endpoint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRoute
  ApiPublicEchofaceEndpointRoute: typeof ApiPublicEchofaceEndpointRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/echoface/$endpoint': {
      id: '/api/public/echoface/$endpoint'
      path: '/api/public/echoface/$endpoint'
      fullPath: '/api/public/echoface/$endpoint'
      preLoaderRoute: typeof ApiPublicEchofaceEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  ApiPublicEchofaceEndpointRoute: ApiPublicEchofaceEndpointRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
